routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DomainController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'domain', 'as' => 'domain.'], function() {
    Route::get('create', [DomainController::class, 'create'])->name('create');
    Route::post('store', [DomainController::class, 'store'])->name('store');

    Route::get('update/dns', [DomainController::class, 'editDNS'])->name('dns.edit');
    Route::post('update/dns', [DomainController::class, 'updateDNS'])->name('dns.update');
});

Route::get('/', function () { return redirect(route('domain.create')); });

app/Models/Client.php
<?php

namespace App\Models;

class Client extends Model
{
    public $id;
    public $legal;
    public $nameLocal;
    public $birthday;
    public $emails = [];
    public $phones = [];
    public $addressLocal = [
        'index', 'country', 'city', 'street'
    ];
    public $identity = [
        'type', 'series', 'number', 'issuer', 'issued'
    ];
}

app/Models/Domain.php
<?php

namespace App\Models;

class Domain extends Model
{
    public $id;
    public $name;
    public $nservers;
    public $delegated;

    /**
     * Конвертирует NS из строки в массив
     * @param string $nservers – NS в виде строки
     * @return array – NS в виде массива
     */
    public function convertNS(string $nservers): array
    {
        $nservers = explode("\r\n", $this->nservers);
        return $nservers;
    }

    /**
     * Rонвертирует домен в ACE или IDN в зависимости от параметра $to
     * @param string $domain - домен в формате "name.zone"
     * @param string $to - по умолчанию 'ACE'
     * @return string
     */
    public function convert(string $domain, string $to = 'ace'): string
    {
        $to = strtolower($to);

        switch($to) {
            case 'ace': $domain = idn_to_ascii($domain, IDNA_DEFAULT, INTL_IDNA_VARIANT_UTS46); break;
            case 'idn': $domain = idn_to_utf8($domain, IDNA_DEFAULT, INTL_IDNA_VARIANT_UTS46); break;
            default: throw new \Exception("Can't convert domain to {$to}");
        }

        return $domain;
    }
}

app/Models/Model.php
<?php

namespace App\Models;

class Model
{
    public function __construct(array $params)
    {
        $this->set($params);
    }

    public function __get($name)
    {
        return $this->$name;
    }

    public function get()
    {
        return collect(get_object_vars($this));
    }

    /**
     * Устанавливает значения модели из массива
     * @param bool $skip_if_exists - по умолчанию false. В зависимости от параметра, при установке значения оно не будет
     *                               перезаписываться, если уже существует
     */
    public function set(array $params, bool $skip_if_exists = false)
    {
        foreach($params as $key => $value) {
            if($skip_if_exists && isset($this->$key)) {
                continue;
            }

            $this->$key = $value;
        }
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DomainController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\DomainRequest;
use App\Http\Requests\DomainUpdateDNSRequest;
use App\Repositories\ApiRepository;
use App\Models\{Client, Domain};

class DomainController extends Controller
{
    protected $api;

    public function __construct(ApiRepository $api)
    {
        $this->api = $api;
    }


    public function create()
    {
        return view('domain.create');
    }

    public function store(DomainRequest $request)
    {
        // получаем данные клиента из формы
        $client = $request->except(['domain', '_token']);
        // получаем имя создаваемого домена
        $domain = $request->safe()->only('domain')['domain'];

        $client = new Client($client);
        $domain = new Domain(['name' => $domain]);

        // создаем клиента и домен
        $this->api->createClient($client);
        $this->api->createDomain($domain, $client);

        return back()->with('success', true);
    }

    public function editDNS()
    {
        return view('domain.update-dns');
    }

    public function updateDNS(DomainUpdateDNSRequest $request)
    {
        $request = $request->validated();

        $domain = new Domain($request);
        // пока не понял как конвертацию имени домена и строки с ns в массив
        // перенести в момент установки или получения значения из Domain (т.е. внутрь класса Domain)
        // "не понял как" — в смысле без создания костыля. Так что пока тут:
        $domain->set([
            'name' => $domain->convert($domain->name),
            'nservers' => $domain->convertNS($domain->nservers)
        ]);

        // обновляем NS
        $this->api->updateDomain($domain, ['nservers', 'delegated']);

        return back()->with('success', true);
    }
}

resources/views/blocks/errors.blade.php
@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/blocks/nav.blade.php
<div class="text-center mb-2">
    <a href="{{ route('domain.create') }}">Создание домена</a> /
    <a href="{{ route('domain.dns.edit') }}">Изменение ДНС</a>
</div>

resources/views/blocks/success.blade.php
@if(session('success'))
    <div class="alert alert-success">
        {{ $message }}
    </div>
@endif

resources/views/domain/create.blade.php
@extends('layouts.app')

@section('title', 'Создание домена')

@section('content')
<div class="row">

<div class="mx-auto mt-3 col-lg-6">
    @include('blocks.nav')
    <h4 class="mb-3">Регистрация домена</h4>

    @include('blocks.success', ['message' => 'Клиент и домен созданы.'])
    @include('blocks.errors')

    <form method="post" action="{{ route('domain.store') }}">
        <div class="row g-3">
            <div class="col-12">
                <label for="domain" class="form-label">Домен</label>
                <input type="text" class="form-control" name="domain" value="{{ old('domain') }}" id="domain" placeholder="example.ru" required>
            </div>
            <div class="col-12">
                <label for="legal" class="form-label">Юридическая организация</label>
                <select class="form-select" name="legal" id="legal" required>
                    <option value="org">Юридическое лицо</option>
                    <option value="person" selected>Физическое лицо</option>
                    <option value="proprietor">Индивидуальный предприниматель</option>
                </select>
            </div>
            <div class="col-12">
                <label for="nameLocal" class="form-label">ФИО</label>
                <input type="text" class="form-control" name="nameLocal" value="{{ old('nameLocal') }}" id="nameLocal" required>
            </div>

            <div class="col-12">
                <label for="birthday" class="form-label">День рождения</label>
                <input type="date" class="form-control" name="birthday" value="{{ old('birthday') }}" id="birthday" required>
            </div>

            <div class="row gy-3">
                <div class="col-md-6">
                    <label for="email" class="form-label">Email</label>
                    <input type="text" class="form-control" name="emails[]" value="{{ old('emails.0') }}" id="email" required>
                </div>

                <div class="col-md-6">
                    <label for="phone" class="form-label">Телефон</label>
                    <input type="text" class="form-control" name="phones[]" value="{{ old('phones.0') }}" id="phone" placeholder="+7 999 001 00 00" required>
                </div>
            </div>

            <hr class="my-4">
            <h5 class="">Адрес</h5>

            <div class="row gy-3">
                <div class="col-md-2">
                    <label for="index" class="form-label">Индекс</label>
                    <input type="text" class="form-control" name="addressLocal[index]" value="{{ old('addressLocal.index') }}" id="index" required>
                </div>
                <div class="col-md-3">
                    <label for="country" class="form-label">Страна</label>
                    <select class="form-select" name="addressLocal[country]" value="{{ old('addressLocal.coountry') }}" id="country" required>
                        <option value="RU">Россия</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label for="city" class="form-label">Город</label>
                    <input type="text" class="form-control" name="addressLocal[city]" value="{{ old('addressLocal.city') }}" id="city" required>
                </div>
                <div class="col-md-4">
                    <label for="street" class="form-label">Улица</label>
                    <input type="text" class="form-control" name="addressLocal[street]" value="{{ old('addressLocal.street') }}" id="street" required>
                </div>
            </div>

            <hr class="my-4">
            <h5 class="">Паспорт</h5>

            <input type="hidden" name="identity[type]" value="passport">
            <div class="row gy-3">
                <div class="col-md-6">
                    <label for="series" class="form-label">Серия</label>
                    <input type="text" class="form-control" name="identity[series]" value="{{ old('identity.series') }}" id="series" required>
                </div>

                <div class="col-md-6">
                    <label for="number" class="form-label">Номер</label>
                    <input type="text" class="form-control" name="identity[number]" value="{{ old('identity.number') }}" id="number" required>
                </div>
            </div>

            <div class="col-12">
                <label for="issuer" class="form-label">Кем выдан</label>
                <input type="text" class="form-control" name="identity[issuer]" value="{{ old('identity.issuer') }}" id="issuer" required>
            </div>

            <div class="col-12">
                <label for="issued" class="form-label">Дата выдачи</label>
                <input type="date" class="form-control" name="identity[issued]" value="{{ old('identity.issued') }}" id="issued" required>
            </div>

            <button class="my-5 w-100 btn btn-primary btn-lg" type="submit">Отправить</button>
            @csrf
        </form>
</div>
</div>
@endsection

resources/views/domain/update-dns.blade.php
@extends('layouts.app')

@section('title', 'Обновление DNS')

@section('content')
<div class="row">

<div class="mx-auto mt-3 col-lg-6">
    @include('blocks.nav')
    <h4 class="mb-3">Обновление ДНС</h4>

    @include('blocks.success', ['message' => 'DNS отредактирован'])
    @include('blocks.errors')

    <form method="post" action="{{ route('domain.dns.update') }}">
        <div class="row g-3">
            <div class="col-12">
                <label for="name" class="form-label">Домен</label>
                <input type="text" class="form-control" name="name" value="{{ old('domain') }}" id="name" required>
            </div>
            <div class="col-12">
                <label for="ns" class="form-label">Список NS</label>
                <textarea class="form-select" name="nservers" id="ns" required>{{ old('ns') }}</textarea>
            </div>

            <button class="my-5 w-100 btn btn-primary btn-lg" type="submit">Отправить</button>
            @csrf
        </form>
</div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>@yield('title')</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>